
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: git checkout $tag
        run: git checkout $(cat ${GITHUB_EVENT_PATH} | jq -r ".ref")
      - name: Build the Docker image
        run: |
          docker build . \
          --file Dockerfile \
          --tag docker.pkg.github.com/syuchan1005/docker-onamae-ddns/onamae_ddns:$(cat ${GITHUB_EVENT_PATH} | jq -r ".ref" | grep -Po "([^/]+)$")
      - name: Deploy github-package-registry (docker)
        run: |
          docker login docker.pkg.github.com -u syuchan1005 -p "${{ secrets.GITHUB_TOKEN }}" \
          && docker push docker.pkg.github.com/syuchan1005/docker-onamae-ddns/onamae_ddns:$(cat ${GITHUB_EVENT_PATH} | jq -r ".ref" | grep -Po "([^/]+)$")
